export const CURRENT_PERCEPTUAL_HASH_VERSION = 1;
export const IS_EXACT_DUPLICATE_DISTANCE = -1;
export const USER_PERCEPTUAL_HASH_MULTIPLIER = 1/1000000;
export const DUP_LIKELY_PERCEPTUAL_HASH_DISTANCE = 1000000;
export const ALT_LIKELY_PERCEPTUAL_HASH_DISTANCE = 55000000;
export const REASONABLE_PERCEPTUAL_HASH_DISTANCE = 62000000;
export const MAX_PERCEPTUAL_HASH_DISTANCE = 80000000;
export const COMPARE_FILES_FOR_DUPLICATE_JOB_TYPE = "compare-files-for-duplicates";